#!/usr/bin/env bash

echo "== deploying a contanirized 3-tier architecture using aws fargate "

STACK_NAME="ECS-Fargate"

aws cloudformation deploy \
--template-file template.yaml \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--region us-east-1 \
--stack-name $STACK_NAME

