name: Deploy Backend Staging

on:
  push:
    branches:
      - develop
    paths:
      - 'backend/**'
      - '.github/workflows/backend-staging-deploy.yaml'
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: backend
  ECS_CLUSTER: FargateClusterStaging
  ECS_SERVICE: backend-service-staging
  ECS_TASK_DEFINITION: backend-task-staging
  ALB_URL: ${{ secrets.STAGING_ALB_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: WORKFLOW VERSION TEST
        run: |
          echo "VERSION-20260614-TEST"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
            -t backend:${{ github.sha }} \
            ./backend

      - name: Tag Docker Image
        run: |
          docker tag \
            backend:${{ github.sha }} \
            ${{ steps.login-ecr.outputs.registry }}/backend:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/backend:${{ github.sha }}

      - name: Download Current Task Definition
        run: |
          aws ecs describe-task-definition \
            --task-definition backend-task-staging \
            --query taskDefinition > task-definition.json

      - name: Update Image in Task Definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        id: render-task-definition
        with:
          task-definition: task-definition.json
          container-name: backend
          image: ${{ steps.login-ecr.outputs.registry }}/backend:${{ github.sha }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2.4.0
        with:
          task-definition: ${{ steps.render-task-definition.outputs.task-definition }}
          service: backend-service-staging
          cluster: FargateClusterStaging
          wait-for-service-stability: true

      - name: Health Check
        run: |
          curl -f $ALB_URL/health
